title: Safe at Home Seniors
description: Guides & gear for aging in place in Canada.
remote_theme: pages-themes/minimal@v0.2.0

# Required so GitHub Pages loads the theme
plugins:
  - jekyll-remote-theme
